### ISSUE TITLE
Loki

### ISSUE THREAD

**Issue by hongbo-miao** [hongbo-miao/hongbomiao.com#10597]
- https://github.com/grafana/loki

# Helm chart

- https://github.com/grafana/loki/tree/main/production/helm/loki
- Issues
  - pod has unbound immediate PersistentVolumeClaims
    - Related issues:
      - https://github.com/grafana/loki/issues/14892
    - Solution: Add `storageClass` and also make sure enough nodes, otherwise will get `didn't match pod anti-affinity rules` error.
       ```yaml
		deploymentMode: SimpleScalable
		backend:
		  persistence:
		    storageClass: production-hm-loki-storage-class
		read:
		  persistence:
		    storageClass: production-hm-loki-storage-class
		write:
		  persistence:
		    storageClass: production-hm-loki-storage-class
		```
  - Cannot set resources for `results-cache` pod which has two containers `memcached` and `exporter`
    - Related issues:
      - https://github.com/grafana/loki/issues/13755
    - My question: https://community.grafana.com/t/how-to-set-resource-limit-for-exporter-container-in-the-results-cache-pod/141271
