### ISSUE TITLE
Show Jaeger icons in Linkerd UI

### ISSUE THREAD

**Issue by Hongbo-Miao** [Hongbo-Miao/hongbomiao.com#2848]
### Linkerd 2.10 (latest)

- https://github.com/linkerd/linkerd2/discussions/6464
- https://linkerd.io/2.10/tasks/distributed-tracing/
- https://linkerd.slack.com/archives/C89RTCWJF/p1616505420138100?thread_ts=1616505287.137800&cid=C89RTCWJF

  Use `-f` or `--values` for latest Linkerd version.

```shell
linkerd install --values=kubernetes/linkerd/config.yaml --disable-heartbeat | kubectl apply --filename=-
```
```yaml
tracing:
  enabled: true
  collector:
    resources:
      cpu:
        limit: 100m
        request: 10m
      memory:
        limit: 100Mi
        request: 50Mi
```

### Linkerd 2.9

- https://linkerd.io/2.9/tasks/distributed-tracing/
- https://www.tarun.xyz/jaeger-linkerd-integration/
- https://linkerd.io/2.9/tasks/enabling-addons/
