### ISSUE TITLE
Make Kafka be accessible for clients running outside of Kubernetes

### ISSUE THREAD

**Issue by Hongbo-Miao** [Hongbo-Miao/hongbomiao.com#8042]
- Load balancer (Cannot on local k3s Kubernetes)
  - Tutorial: https://strimzi.io/blog/2019/05/13/accessing-kafka-part-4/
  - (Not working) https://cloud-native.slack.com/archives/CMH3Q3SNP/p1658935527055969?thread_ts=1658917401.523259&cid=CMH3Q3SNP
    ```yaml
        listeners:
          - name: plain
            port: 9092
            type: internal
            tls: false
          - name: tls
            port: 9093
            type: internal
            tls: true
          - name: lbalancer
            port: 9195
            type: loadbalancer
            tls: false
            configuration:
              createBootstrapService: false
    ```
  - (Not helpful) https://stackoverflow.com/questions/69752073/external-access-to-kafka-using-strimzi
  - My questions:
    - (Solved) https://stackoverflow.com/questions/76018289/how-to-use-different-load-balancer-ports-for-kafka-bootstrap-and-brokers-created
- Ingress
  - Tutorial: https://strimzi.io/blog/2019/05/23/accessing-kafka-part-5/
  - Kafka broker pod never created
    - (not helpful) https://github.com/orgs/strimzi/discussions/4292
  - My questions:
    - (Solved) https://stackoverflow.com/questions/76019561/ssl-handshake-failed-using-ingress-way-for-kafka-created-by-strimzi
    - (Solved) https://stackoverflow.com/questions/76020537/strimzi-kafka-brokers-not-created-because-of-ingress-does-not-contain-a-valid-i
